---
#- import_tasks: load_vars.yml

- hosts: Proxmox
  any_errors_fatal: true
  tasks:

  - name: "Display Host info"
    debug:
      msg:
        - "Host: {{ ansible_fqdn }}"
        - "IP: {{ ansible_default_ipv4['address'] }}"
        - "OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
        - "Kernel: {{ ansible_kernel_version }}"

  - name: "Check if initial setup has already been performed"
    stat: path="/root/.init_setup_done"
    register: already_prep

  - name: "Fail if already run on host"
    fail: msg="Initial Setup Already completed!"
    when: already_prep.stat.exists


# Commented for test, remember to remove before push!
#
#  - name: "create lock file"
#    file: path="/root/.init_setup_done" state=touch
  
#  - name: "Update cache and execute dist-upgrade"
#    apt:
#      update_cache: yes
#      upgrade: dist
      #cache_valid_time: 3600 -- We need to update the cache every time, if no enterprise key installed we should recive an Unauthorized message

  - name: "Install utils"
    package:
      name:
        - vim
        - screen
        - unzip
        - nethogs
        - iftop
        - htop
      state: latest
    
  - name: "Install cv4pve-autosnap by Corsinvest"
    unarchive:
      src: "https://github.com/Corsinvest/cv4pve-autosnap/releases/download/v1.11.0/cv4pve-autosnap-linux-x64.zip"
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Creates a cron for auto-snapshot
    ansible.builtin.cron:
      name: proxmox autosnap
      minute: "55"
      hour: "20"
      user: root
      job: /usr/local/bin/cv4pve-autosnap --host=localhost --username="userbackup@pve" --password="mypassword" --vmid="all" snap --label="daily" --keep=4 >> /tmp/px-autosnap.log
      cron_file: 10-autosnap-px