---
#- import_tasks: load_vars.yml

- hosts: Proxmox
  any_errors_fatal: true
  tasks:

  - name: "Display Host info"
    debug:
      msg:
        - "Host: {{ ansible_fqdn }}"
        - "IP: {{ ansible_default_ipv4['address'] }}"
        - "OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
        - "Kernel: {{ ansible_kernel_version }}"

  - name: "Check if initial setup has already been performed"
    stat: path="/root/.init_setup_done"
    register: already_prep

  - name: "Fail if already run on host"
    fail: msg="Initial Setup Already completed!"
    when: already_prep.stat.exists

  - name: "create lock file"
    file: path="/root/.init_setup_done" state=touch
  
  - name: "Update cache and execute dist-upgrade"
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: dist


 # - name: "Upgrade the OS (apt-get dist-upgrade)"
 #     apt:
 #     upgrade: dist

  - name: "Install utils"
    apt:
      name:
        - vim
        - screen
        - unzip
        - nethogs
        - iftop
        - htop
      state: latest
    
